### ISSUE TITLE
2 erroneous information

### ISSUE THREAD

**Issue by giuseppec** [jakobbossek/smoof#49]
Hi,

1)

```{r}
getTags(makeEggholderFunction())
# [1] "continuous"     "differentiable" "non-separable"  "scalable"       "multimodal"    
```
says that the Function is scalable, but I can't set the number of dimensions. 

2)
According to https://sites.google.com/site/gotestfunctions/multimodal-function-list/-23-giunta and https://sites.google.com/site/gotestfunctions/multimodal-function-list/-23-giunta the global optimum for the giunta function is at `0.06447...` but
```{r}
getGlobalOptimum(makeGiuntaFunction())
# $param
#         x1        x2
# 1 0.4583428 0.4583428
#
# $value
# [1] 0.06463
```

**Comment by jakobbossek** [comment]
Thanks for the report. Going to fix this within the next hour.

**Comment by giuseppec** [comment]
And:, Exponential Function has a multimodal tag?

**Comment by jakobbossek** [comment]
Ok, there is a FIXME in the Eggholder function. It is implemented as a scalable function, but I did not figure out the global optimum for dimensions > 2L. That's why I removed the `dimension` argument for this special generator. For now I will remove the `scalable` tag.

Fixed the other two issues as well.

Let's leave this open for now. Maybe you will find some more minor issues. Unfortunately for some function there exist different sources with different opt value specifications.

**Comment by giuseppec** [comment]
```r
getGlobalOptimum(makeAlpine02Function(2))
# $param
#     x1    x2
# 1 7.917 7.917
# 
# $value
# [1] 7.884864
```
but in http://infinity77.net/global_optimization/test_functions_nd_A.html it says that 
f(x_i) = -6.1295 for all i=1,...,n

**Comment by jakobbossek** [comment]
Yeah, I remember that Alpine02 case. I think the specification on the website is wrong.
The function is implemented correctly via `prod(sqrt(x) * sin(x)). Take a look at the 3D plot:
```splus
fn = makeAlpine02Function(2L)
plot3D(fn)
```
1. Since the function is expected to be maximized, a negative global optimum is not possible.
2. The 3D plot revelas, that the optimum has a value above 7. In fact `fn(c(7.917, 7.917))` results in `7.886`

**Comment by giuseppec** [comment]
Aggreed. I think they used the gobal "minimum" of the function, which is indeed f(x_i) = -6.1295, however, not at `c(7.917, 7.917)`. So this function wants to be maximized and not minimized.

**Comment by giuseppec** [comment]
Further strange things:

1) In http://infinity77.net/global_optimization/test_functions_nd_B.html it says "Global optimum: f(x_i) = 0 for \mathbf{x} = [-10, 0]", but the function is defined in "x_1 \in [-15, -5], x_2 \in [-3, 3]"

```{r}
getGlobalOptimum(makeBukinN2Function())$value
# [1] 0
makeBukinN2Function()(c(-15,-3))
# [1] -424.75
``` 
also `plot3D(makeBukinN2Function())` looks a bit strange, right? It is at least completely different from [![http://infinity77.net/global_optimization/_images/Bukin02.png](http://infinity77.net/global_optimization/_images/Bukin02.png)](http://infinity77.net/global_optimization/_images/Bukin02.png)

2) This seems to be a good page http://al-roomi.org/component/tags/tag/20-matlab. They have, for example information about the global optimum for the [michalewicz function]
(http://al-roomi.org/benchmarks/unconstrained/n-dimensions/197-michalewicz-s-function) (for n=1,2).

3) 
```{r}
plot3D(makeCosineMixtureFunction(2)) # looks like a maximum, but:
getGlobalOptimum(makeCosineMixtureFunction(2))
```
```
$param
  x1 x2
1  0  0

$value
[1] -0.2

$is.minimum
[1] TRUE
```
same for Keane.

4) `plot3D(makeBochachevskyFunction(2))` does  not look like http://al-roomi.org/benchmarks/unconstrained/2-dimensions/10-bohachevsky-s-function-no-1
Also:
```r
makeBochachevskyFunction(2)(c(-15,-0.3))
# -13.49639, although getGlobalOptimum says that 0 is the optimum
```

**Comment by jakobbossek** [comment]
Thanks for the report. Going to check this soon.

**Comment by jakobbossek** [comment]
Ok, I fixed all the stuff above. For the Rosenbrock function there obviously exist different function definitions. I now changed the defintion to the specification of [http://infinity77.net/global_optimization/test_functions_nd_R.html](infinity77).

The implementation of the BukinN2 function is given by:
```splus
makeBukinN2Function = function() {
  makeSingleObjectiveFunction(
    name = "Bukin Function N. 2",
    fn = function(x) {
      100 * (x[2] - 0.01 * x[1]^2 + 1) + 0.01 * (x[1] + 10)^2
    },
    par.set = makeNumericParamSet(
      len = 2L,
      id = "x",
      lower = c(-15, -3),
      upper = c(-5, 3),
      vector = TRUE
    ),
    tags = attr(makeBukinN2Function, "tags"),
    global.opt.params = c(-10, 0),
    global.opt.value = 0
  )
}
```
This corresponds with the [http://infinity77.net/global_optimization/test_functions_nd_B.html](infinity77) formula, but the 3D plot does not resemble the plot given on the website. If you have a look at the formula, than you can see, that the contribution of the squared x_1 value is minimal due to the 0.01 factors and hence the function cannot have this special shape as given on the website.

**Comment by jakobbossek** [comment]
@giuseppec: What do you think about the Bukin02 function (see my last comment here)?

**Comment by giuseppec** [comment]
Hm, I googled a little bit and it is difficult to find more infos for this function. I think there is more info in "Differential Evolution: Fundamentals and Applications in Electrical Engineering (Anyong Qing)" but I don't have access to this book right now. 

What about removing this Bukin02 function and replace it with http://al-roomi.org/benchmarks/unconstrained/2-dimensions/51-bukin-s-function-no-4
 and http://al-roomi.org/benchmarks/unconstrained/2-dimensions/52-bukin-s-function-no-6, which seem to be much more "well-known"? By plotting this Bukin02 function, it does not seem to be a "cool" function that should be optimized...

**Comment by jakobbossek** [comment]
Ok, I found the Bukin02 function definition in two more papers. It is correct. As a consequence, the plot on the infinity77 website must be wrong. Not removing for now.

**Comment by jakobbossek** [comment]
Closing for now. Reopen if needed.
