### ISSUE TITLE
add convertToMinimization and convertToMaximization functions?

### ISSUE THREAD

**Issue by giuseppec** [jakobbossek/smoof#69]
These two function would be helpful.

It should take a smoof function `f(x)` and create another smoof function which is simply `-f(x)`, so that the global optimum will change from minimum to maximum and vice versa:

For example:
```
alpine = makeAlpine02Function(2)
# > alpine(c( 7.917, 7.917))
# [1] 7.885601
alpine.min = convertToMinimization(alpine02)
# > alpine(c( 7.917, 7.917))
# [1] -7.885601
```

Note that `attr(*, "minimize")` should also be changed with `convertToMinimization` or `convertToMaximization`.

**Comment by jakobbossek** [comment]
I had already some unfinished code in my todo-files for that. Going to commit in the evening.

**Comment by jakobbossek** [comment]
Added exported functions `convertToMinimization` and `convertToMaximization`.
Both expect a single-objective smoof function only. The obvious solution would be to write a wrapper around the passed function which simply multiplies by -1. However, in order to avoid another wrapper function I directly modify the body of the passed function.

Does this work for you?

**Comment by jakobbossek** [comment]
ping

**Comment by giuseppec** [comment]
For my needs it seems to work. Thx. I'll close and reopen if I encounter any issues.

**Comment by jakobbossek** [comment]
Ok. Great.
